[package]
name = "mwax_stats"
version = "0.1.2"
readme = "README.md"
homepage = "https://github.com/MWATelescope/mwax_stats"
repository = "https://github.com/MWATelescope/mwax_stats"
authors = [    
    "Greg Sleap <greg.sleap@curtin.edu.au>"
]
edition = "2018"
license = "MPL-2.0"
keywords = ["radioastronomy", "mwa", "astronomy", "mwalib"]
categories = ["science"]
exclude = ["tests/*", ".vscode/*", ".github/*"]

[dependencies]
clap = "2.33"
env_logger = "0.9"
file-utils = "0.1.5"
log = "0.*"
mwalib = "0.11.*"